                                #DESIGN AND DEVELOPED BY SHIVANT KUMAR PANDEY
                                           #CHITKARA UNIVERSITY HP


#Convert the 0 into a number so we can add scores
score = 0
score = int(score)
print('****************************************QUIZ ZONE OF CODER2HACKER *****************************')
#Please enter your Name to Proceed:
name = input("What is your name?")
name = name.title()
print("""Hello {}, welcome to Quiz night! 
You will get presented questions on your windows.
Enter the appropriate number to answer the question
Good luck!""".format(name))

print('*************************************************')

#Question1
print('QUIZ:1')
print(""" What is the primary interactive method of communication used by humans?
1.Listening 
2.Speaking
3.Writting 
4.All of these""")

answer1 = "2"
response1 = input("Your answer is:")

if (response1 != answer1):
    print("Sorry, that is incorrect!")
else:
    print("Well done! " + response1 + " is correct!")
    score = score + 1

print("Your current score is " + str(score) + " out of 10")


print('****************************************************************')


#Question2

print('QUIZ:2')
print("""What are the undesirable properties of knowledge?
1.  Voluminous
2. Difficult to characteriszes
3. Variablity
4. All of the above""")

answer2 = "4"
response2 = input("Your answer is:")

if (response2 != answer2):
    print("Sorry, that is incorrect!")
else:
    print("Well done! " + response2 + " is correct!")
    score = score + 1

print("Your current score is " + str(score) + " out of 10")


print('****************************************************************')

#Question3
print('QUIZ:3')
print(""" Compromising a user’s session for exploiting the user’s data and do malicious activities or misuse user’s credentials is called
1.Session Hijacking
2. Session Fixation 
3. Cookie stuffing
4. Session Spying""")

answer3 = "1"
response3 = input("Your answer is:")

if (response3 != answer3):
    print("Sorry, that is incorrect!")
else:
    print("Well done! " + response3 + " is correct!")
    score = score + 1

print("Your current score is " + str(score) + " out of 10")



print('****************************************************************')

#Question4
print('QUIZ:4')
print("""Who is the ‘demi-god’ or the ‘great creator’ who fished NZ out from the sea?
1. Zeus
2. Hercules
3. Maui
4. Maori""")

answer4 = "3"
response4 = input("Your answer is:")

if (response4 != answer4):
    print("Sorry, that is incorrect!")
else:
    print("Well done! " + response4 + " is correct!")
    score = score + 1

print("Your current score is " + str(score) + " out of 10")


print('****************************************************************')

#Question5
print('QUIZ:5')
print("""Which of them is not a wireless attack?
1. Eavesdropping
2. MAC Spoofing
3. Wireless Hijacking
4. Phishing""")

answer5 = "4"
response5 = input("Your answer is:")

if (response5 != answer5):
    print("Sorry, that is incorrect!")
else:
    print("Well done! " + response5 + " is correct!")
    score = score + 1

print("Your total score is " + str(score) + " out of 10")
print("Thank you for playing {}, goodbye!".format(name))


print('****************************************************************')

#Question6
print('QUIZ:6')
print("""An attempt to harm, damage or cause threat to a system or network is broadly termed as :
1. cyber crime
2. cyber attack
3. system hijacking
4. Digital crime""")

answer5 = "2"
response5 = input("Your answer is:")

if (response5 != answer5):
    print("Sorry, that is incorrect!")
else:
    print("Well done! " + response5 + " is correct!")
    score = score + 1

print("Your total score is " + str(score) + " out of 10")
print("Thank you for playing {}, goodbye!".format(name))


print('****************************************************************')

#Question5
print('QUIZ:7')
print("""Which method of hacking will record all your keystrokes?
1. Keyhijacking
2. Keyjacking
3. Keylogging
4. Keyboard monitoring""")

answer5 = "3"
response5 = input("Your answer is:")

if (response5 != answer5):
    print("Sorry, that is incorrect!")
else:
    print("Well done! " + response5 + " is correct!")
    score = score + 1

print("Your total score is " + str(score) + " out of 10")
print("Thank you for playing {}, goodbye!".format(name))


print('****************************************************************')



#Question8
print('QUIZ:8')
print(""" Which of the following is an example of a deterministic algorithm?
1. PCA
2. k-means
3. out-shoft
4. none""")

answer5 = "1"
response5 = input("Your answer is:")

if (response5 != answer5):
    print("Sorry, that is incorrect!")
else:
    print("Well done! " + response5 + " is correct!")
    score = score + 1

print("Your total score is " + str(score) + " out of 10")
print("Thank you for playing {}, goodbye!".format(name))


print('****************************************************************')


#Question9
print('QUIZ:9')
print(""" The protocol data unit(PDU) for the application layer in the Internet stack is
1. Segment
2. Datagram
3. Message
4. Frame""")

answer5 = "3"
response5 = input("Your answer is:")

if (response5 != answer5):
    print("Sorry, that is incorrect!")
else:
    print("Well done! " + response5 + " is correct!")
    score = score + 1

print("Your total score is " + str(score) + " out of 10")
print("Thank you for playing {}, goodbye!".format(name))


print('****************************************************************')


#Question10
print('QUIZ:10')
print(""" The protocol data unit(PDU) for the application layer in the Internet stack is
1. Segment
2. Datagram
3. Message
4. Frame""")

answer5 = "3"
response5 = input("Your answer is:")

if (response5 != answer5):
    print("Sorry, that is incorrect!")
else:
    print("Well done! " + response5 + " is correct!")
    score = score + 1

print("Your total score is " + str(score) + " out of 11")
print("Thank you for playing {}, goodbye!".format(name))


print('****************************************************************')



#Question11
print('QUIZ:11')
print("""Which of the following transport layer protocolss is used to support electronic mail?
1. SMTP
2. IP
3. TCP
4. UPD""")

answer5 = "3"
response5 = input("Your answer is:")

if (response5 != answer5):
    print("Sorry, that is incorrect!")
else:
    print("Well done! " + response5 + " is correct!")
    score = score + 1

print("Your total score is " + str(score) + " out of 11")
print("Thank you for playing {}, goodbye!".format(name))

print('************************************************************************')
print('THANKS FOR SHOWING INTEREST IN PLAYING THIS QUIZ:');






